### ISSUE TITLE
grok插件需要正则解析的字段和正则表达式怎么一一对应？

### ISSUE THREAD

**Issue by linrongfu26** [DTStack/jlogstash-filter-plugin#2]
grok插件有两个字段，一个是srcs，是个list结构，一个是patterns字段，是个map，srcs中需要解析的字段是怎么和map中的正则表达式关联起来的？

**Comment by yangsishu** [comment]
srcs 配置的是你map中需要解析的属性，patterns 是你写的正则，现在没有一对一匹配，而是全部匹配。

**Comment by yangsishu** [comment]
这个现在的设计没有一一匹配是不合理，后面要改掉，或者你们也可以自己改，我们也需要第三方的开发者一起参与进来
