### ISSUE TITLE
grok插件bug

### ISSUE THREAD

**Issue by Dave-Zhou** [DTStack/jlogstash-filter-plugin#3]
首先如果使用文档所说，如果:grok自带的已经有了,正则表达式不需要写，列如:{"%{COMBINEDAPACHELOG}":""} ，实际上并不会执行，因为代码中if(StringUtils.isNotBlank(value)){
					grok.addPattern(key,value);
					grok.compile(key);
				}，
如果为空，并不会grok.complie，
然后grok.match方法代码如下：
if (compiledNamedRegex == null || StringUtils.isBlank(text)) {
      return Match.EMPTY;
    }
意味着grok，并没有生效因为没有compile,compiledNamedRegex永远为null

**Comment by yangsishu** [comment]
已经修复了，在master分支上
