### ISSUE TITLE
grok bug,想要通过加载自定义pattern文件，达到logstash的效果，

### ISSUE THREAD

**Issue by Dave-Zhou** [DTStack/jlogstash-filter-plugin#4]
本来我想改了grok bug1的问题，可以加载自定义的Pattern来完成自己想要的解析，结果发现加载文件的方式有如下问题：1.代码中while ((line = br.readLine()) != null) {
				Matcher m = pattern.matcher(line);
				if (m.matches()) {
					grok.addPattern(m.group(1), m.group(2));
//					grok.compile(m.group(1));
				}
强制compile每一个pattern，这是我注释了这个代码，
2.跟着bug1的问题，我修改了代码，方法addFromPatternMap：
if(StringUtils.isNotBlank(value)){
					grok.addPattern(key,value);
					grok.compile(key);
				} else {
					grok.compile(key);
				}
这样依然会找不到我想要的结果，原因在于加载顺序的问题，代码中先加载了Map后加载文件，所以找不到我自定义的名字调整后如下：
public void prepare() {
		if(grok==null){
			try {
				grok = new Grok();
				addPatternToGrok(grok);
				addFromPatternFile();
				addFromPatternMap();
			} catch (Exception e) {
				logger.error("grok compile is error:", e);
				System.exit(1);
			}
	
		}
    }
能够正常达到预期

**Comment by yangsishu** [comment]
已经修复
