### ISSUE TITLE
Tomcat Access log filter Error 

### ISSUE THREAD

**Issue by walterxue** [DTStack/jlogstash-filter-plugin#6]
大神！在我環境內要將tomcat 的 Accesslog 從 filebeat 透過 jlogstash filter 作處理會出現錯誤，懇求協助

ERROR com.dtstack.jlogstash.filters.JGrok [JGrok.java:198] - grok filter is error: {}

設定如下
- JGrok:
srcs: {["message"]}
patterns: {"%{COMBINEDAPACHELOG}":""}

AccessLog example:
- "0.0.0.0" 1.1.1.1 - U-9999 [16/May/2018:12:54:08 +0800] "GET /API/API.jsp HTTP/1.1" 200 25 "https://aa.example.com/USER/B/A/index.jsp" "Mozilla/5.0 (Linux; Android 5.1.1; vivo Y51 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.2125.102 Mobile Safari/537.36 VivoBrowser/5.4.12"

**Comment by yangsishu** [comment]
jgrok 的代码有bug 前几天已经修复了，所以你自己拉下master 上 grok 的源码自己本地编译下，现在mvn 库上的grok 插件代码是有bug的

**Comment by yangsishu** [comment]
还有 srcs: {["message"]} 你这个配置错了，srcs是list 结构，这样配置就可以了 ["message"]
